### ISSUE TITLE
Payments failed to send (guess orphan block leads to not enough money)

### ISSUE THREAD

**Issue by goodman3654** [zone117x/node-cryptonote-pool#196]
hi, 

Thanks for zone117x's code. I ran a pool for several months and it runs well in the past few months. It's the first time that I encounter this error(not enough money to pay out). I guess it's caused by orphan block, but have no idea how to fix it. I will appreciate if anyone can help.

orphan block:
<img src=https://i.imgur.com/MTBN2zW.jpg>

wallet rpc error:
<img src=https://i.imgur.com/rqUJP7Z.jpg>

pool error:
<img src=https://i.imgur.com/XqCn2MA.jpg>

**Comment by xikimay** [comment]
I'm facing the same issue, how did you solve it ?

**Comment by goodman3654** [comment]
I transfered enough money to pool wallet, then it can pay out to workers. 
But I didn't figure out the source of this issue, so it will happen again someday...

**Comment by cycleworm** [comment]
i had the same problem today on my pool. its a pity. because it was the 12th block or so that the pool found. so i had to transfer the coins from my private wallet to the pool wallet to keep thinks up. :(

does anybody know if the blockunlocker code works correctly? how high have you guys set the maturity depth? 

thanks

**Comment by phil2cr** [comment]
Hi @cycleworm i face an issue with the payment the pool try to send too much (6000) in a transfer maybe it is to obfuscate the transfert ?
I did set the maturity to 10 but (i use ETN)  but maybe it is a bad idea. 60 is better ?
