### ISSUE TITLE
Understanding how `getTargetHex` function works

### ISSUE THREAD

**Issue by kgritesh** [zone117x/node-cryptonote-pool#223]
Thanks a lot for a great library. I learned a lot about monero and mining pools from this code. However i had couple of questions which i am not able to understand. I guess this is not an issue as much as a request to understand how do we calculate target hash for a job.  As far as i understand  
 from [here](http://learnmeabitcoin.com/guide/difficulty#finding-the-target-using-the-difficulty)   
    
 `target = <max target> / difficulty`

However in the implementation we only take first 4 bytes of the target and reverse them. Infact i saw that even the other open source mining pools does the same thing. I have spent couple of days trying to figure this out, but have still been stumped. Would really appreciate if you could help with this

**Comment by zone117x** [comment]
It's been years since that was figured out. I believe its that way due to basing the target difficulty format on the original mining protocol used by Minergate's mining client. The byte reversal I believe is an endian swap, and the 4 bytes thing is possibly due to not needing the extra precision.
Sorry I can't be of more help.

**Comment by kgritesh** [comment]
@zone117x Thanks a lot for your reply.  I guess i will have to accept it as it is. Thanks anyways for the answer and for opensourcing this. Great learning experience
